### ISSUE TITLE
matter in the media at-rule

### ISSUE THREAD

**Issue by totora0155** [totora0155/postcss-matter#2]
``` css
@media screen and (min-width: xxx) {
  .test {
    matter: xxxxxx;
  }
}
```

result

``` css
.test {
  aaa:aaa;
  bbb:bbb;
  ccc:ccc;
}
```

expect

``` css
@media screen and (min-width: xxx) {
  .test {
    aaa:aaa;
    bbb:bbb;
    ccc:ccc;
  }
}
```
